// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type PlanRun struct {
	ID             string         `json:"id"`
	ScenarioID     string         `json:"scenario_id"`
	Planner        string         `json:"planner"`
	Status         string         `json:"status"`
	CreatedAt      string         `json:"created_at"`
	ParentRunID    sql.NullString `json:"parent_run_id"`
	ActiveEventIds []byte         `json:"active_event_ids"`
	Document       []byte         `json:"document"`
}

type Scenario struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	Name          string `json:"name"`
	SchemaVersion string `json:"schema_version"`
	Document      []byte `json:"document"`
	CreatedAt     string `json:"created_at"`
}
