// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetPlanRun(ctx context.Context, id string) (PlanRun, error)
	GetScenario(ctx context.Context, id string) (Scenario, error)
	GetScenarioBySite(ctx context.Context, siteID string) (Scenario, error)
	InsertPlanRun(ctx context.Context, arg InsertPlanRunParams) error
	ListPlanRunsByScenario(ctx context.Context, arg ListPlanRunsByScenarioParams) ([]PlanRun, error)
	UpsertScenario(ctx context.Context, arg UpsertScenarioParams) error
}

var _ Querier = (*Queries)(nil)
