// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const getPlanRun = `-- name: GetPlanRun :one
SELECT id, scenario_id, planner, status, created_at, parent_run_id, active_event_ids, document
FROM plan_runs
WHERE id = ?
`

func (q *Queries) GetPlanRun(ctx context.Context, id string) (PlanRun, error) {
	row := q.db.QueryRowContext(ctx, getPlanRun, id)
	var i PlanRun
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Planner,
		&i.Status,
		&i.CreatedAt,
		&i.ParentRunID,
		&i.ActiveEventIds,
		&i.Document,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, site_id, name, schema_version, document, created_at
FROM scenarios
WHERE id = ?
`

func (q *Queries) GetScenario(ctx context.Context, id string) (Scenario, error) {
	row := q.db.QueryRowContext(ctx, getScenario, id)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.SchemaVersion,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const getScenarioBySite = `-- name: GetScenarioBySite :one
SELECT id, site_id, name, schema_version, document, created_at
FROM scenarios
WHERE site_id = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetScenarioBySite(ctx context.Context, siteID string) (Scenario, error) {
	row := q.db.QueryRowContext(ctx, getScenarioBySite, siteID)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.SchemaVersion,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlanRun = `-- name: InsertPlanRun :exec
INSERT INTO plan_runs (
    id, scenario_id, planner, status, created_at, parent_run_id, active_event_ids, document
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlanRunParams struct {
	ID             string         `json:"id"`
	ScenarioID     string         `json:"scenario_id"`
	Planner        string         `json:"planner"`
	Status         string         `json:"status"`
	CreatedAt      string         `json:"created_at"`
	ParentRunID    sql.NullString `json:"parent_run_id"`
	ActiveEventIds []byte         `json:"active_event_ids"`
	Document       []byte         `json:"document"`
}

func (q *Queries) InsertPlanRun(ctx context.Context, arg InsertPlanRunParams) error {
	_, err := q.db.ExecContext(ctx, insertPlanRun,
		arg.ID,
		arg.ScenarioID,
		arg.Planner,
		arg.Status,
		arg.CreatedAt,
		arg.ParentRunID,
		arg.ActiveEventIds,
		arg.Document,
	)
	return err
}

const listPlanRunsByScenario = `-- name: ListPlanRunsByScenario :many
SELECT id, scenario_id, planner, status, created_at, parent_run_id, active_event_ids, document
FROM plan_runs
WHERE scenario_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPlanRunsByScenarioParams struct {
	ScenarioID string `json:"scenario_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListPlanRunsByScenario(ctx context.Context, arg ListPlanRunsByScenarioParams) ([]PlanRun, error) {
	rows, err := q.db.QueryContext(ctx, listPlanRunsByScenario, arg.ScenarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanRun
	for rows.Next() {
		var i PlanRun
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.Planner,
			&i.Status,
			&i.CreatedAt,
			&i.ParentRunID,
			&i.ActiveEventIds,
			&i.Document,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScenario = `-- name: InsertScenario :exec
INSERT INTO scenarios (id, site_id, name, schema_version, document, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertScenarioParams struct {
	ID            string `json:"id"`
	SiteID        string `json:"site_id"`
	Name          string `json:"name"`
	SchemaVersion string `json:"schema_version"`
	Document      []byte `json:"document"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) InsertScenario(ctx context.Context, arg InsertScenarioParams) error {
	_, err := q.db.ExecContext(ctx, insertScenario,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.SchemaVersion,
		arg.Document,
		arg.CreatedAt,
	)
	return err
}

const updateScenario = `-- name: UpdateScenario :execrows
UPDATE scenarios
SET
    site_id = ?,
    name = ?,
    schema_version = ?,
    document = ?
WHERE id = ?
`

type UpdateScenarioParams struct {
	SiteID        string `json:"site_id"`
	Name          string `json:"name"`
	SchemaVersion string `json:"schema_version"`
	Document      []byte `json:"document"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateScenario,
		arg.SiteID,
		arg.Name,
		arg.SchemaVersion,
		arg.Document,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
